
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int MOD = 5;
  public static final int ELSE = 16;
  public static final int PLUS = 3;
  public static final int RPAREN = 10;
  public static final int EQUAL = 13;
  public static final int SEMI = 2;
  public static final int IF = 15;
  public static final int LPAREN = 9;
  public static final int LBRACKET = 11;
  public static final int ID = 21;
  public static final int RBRACKET = 12;
  public static final int RB = 19;
  public static final int COMMA = 14;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int BIG = 17;
  public static final int SMALL = 18;
  public static final int UMINUS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "MOD",
  "DIV",
  "TIMES",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "EQUAL",
  "COMMA",
  "IF",
  "ELSE",
  "BIG",
  "SMALL",
  "RB",
  "NUMBER",
  "ID"
  };
}

