/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class ABinaryBuiltin extends PBuiltin
{
    private PTerm _first_;
    private TTBinOp _tBinOp_;
    private PTerm _second_;

    public ABinaryBuiltin()
    {
        // Constructor
    }

    public ABinaryBuiltin(
        @SuppressWarnings("hiding") PTerm _first_,
        @SuppressWarnings("hiding") TTBinOp _tBinOp_,
        @SuppressWarnings("hiding") PTerm _second_)
    {
        // Constructor
        setFirst(_first_);

        setTBinOp(_tBinOp_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new ABinaryBuiltin(
            cloneNode(this._first_),
            cloneNode(this._tBinOp_),
            cloneNode(this._second_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABinaryBuiltin(this);
    }

    public PTerm getFirst()
    {
        return this._first_;
    }

    public void setFirst(PTerm node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TTBinOp getTBinOp()
    {
        return this._tBinOp_;
    }

    public void setTBinOp(TTBinOp node)
    {
        if(this._tBinOp_ != null)
        {
            this._tBinOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tBinOp_ = node;
    }

    public PTerm getSecond()
    {
        return this._second_;
    }

    public void setSecond(PTerm node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._tBinOp_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._tBinOp_ == child)
        {
            this._tBinOp_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PTerm) newChild);
            return;
        }

        if(this._tBinOp_ == oldChild)
        {
            setTBinOp((TTBinOp) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
