/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class ABuiltinLiteral extends PLiteral
{
    private PBuiltin _builtin_;

    public ABuiltinLiteral()
    {
        // Constructor
    }

    public ABuiltinLiteral(
        @SuppressWarnings("hiding") PBuiltin _builtin_)
    {
        // Constructor
        setBuiltin(_builtin_);

    }

    @Override
    public Object clone()
    {
        return new ABuiltinLiteral(
            cloneNode(this._builtin_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABuiltinLiteral(this);
    }

    public PBuiltin getBuiltin()
    {
        return this._builtin_;
    }

    public void setBuiltin(PBuiltin node)
    {
        if(this._builtin_ != null)
        {
            this._builtin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._builtin_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._builtin_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._builtin_ == child)
        {
            this._builtin_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._builtin_ == oldChild)
        {
            setBuiltin((PBuiltin) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
