/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class ADecimalTerm extends PTerm
{
    private TTDec _tDec_;

    public ADecimalTerm()
    {
        // Constructor
    }

    public ADecimalTerm(
        @SuppressWarnings("hiding") TTDec _tDec_)
    {
        // Constructor
        setTDec(_tDec_);

    }

    @Override
    public Object clone()
    {
        return new ADecimalTerm(
            cloneNode(this._tDec_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecimalTerm(this);
    }

    public TTDec getTDec()
    {
        return this._tDec_;
    }

    public void setTDec(TTDec node)
    {
        if(this._tDec_ != null)
        {
            this._tDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tDec_ == child)
        {
            this._tDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tDec_ == oldChild)
        {
            setTDec((TTDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
