/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AFact extends PFact
{
    private PPredicate _predicate_;
    private TTDot _tDot_;

    public AFact()
    {
        // Constructor
    }

    public AFact(
        @SuppressWarnings("hiding") PPredicate _predicate_,
        @SuppressWarnings("hiding") TTDot _tDot_)
    {
        // Constructor
        setPredicate(_predicate_);

        setTDot(_tDot_);

    }

    @Override
    public Object clone()
    {
        return new AFact(
            cloneNode(this._predicate_),
            cloneNode(this._tDot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFact(this);
    }

    public PPredicate getPredicate()
    {
        return this._predicate_;
    }

    public void setPredicate(PPredicate node)
    {
        if(this._predicate_ != null)
        {
            this._predicate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._predicate_ = node;
    }

    public TTDot getTDot()
    {
        return this._tDot_;
    }

    public void setTDot(TTDot node)
    {
        if(this._tDot_ != null)
        {
            this._tDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._predicate_)
            + toString(this._tDot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._predicate_ == child)
        {
            this._predicate_ = null;
            return;
        }

        if(this._tDot_ == child)
        {
            this._tDot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._predicate_ == oldChild)
        {
            setPredicate((PPredicate) newChild);
            return;
        }

        if(this._tDot_ == oldChild)
        {
            setTDot((TTDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
