/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AIriTerm extends PTerm
{
    private TTUnders _tUnders_;
    private TTStr _tStr_;

    public AIriTerm()
    {
        // Constructor
    }

    public AIriTerm(
        @SuppressWarnings("hiding") TTUnders _tUnders_,
        @SuppressWarnings("hiding") TTStr _tStr_)
    {
        // Constructor
        setTUnders(_tUnders_);

        setTStr(_tStr_);

    }

    @Override
    public Object clone()
    {
        return new AIriTerm(
            cloneNode(this._tUnders_),
            cloneNode(this._tStr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIriTerm(this);
    }

    public TTUnders getTUnders()
    {
        return this._tUnders_;
    }

    public void setTUnders(TTUnders node)
    {
        if(this._tUnders_ != null)
        {
            this._tUnders_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tUnders_ = node;
    }

    public TTStr getTStr()
    {
        return this._tStr_;
    }

    public void setTStr(TTStr node)
    {
        if(this._tStr_ != null)
        {
            this._tStr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tStr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tUnders_)
            + toString(this._tStr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tUnders_ == child)
        {
            this._tUnders_ = null;
            return;
        }

        if(this._tStr_ == child)
        {
            this._tStr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tUnders_ == oldChild)
        {
            setTUnders((TTUnders) newChild);
            return;
        }

        if(this._tStr_ == oldChild)
        {
            setTStr((TTStr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
