/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AParamlist extends PParamlist
{
    private TTLpar _tLpar_;
    private PTermlist _termlist_;
    private TTRpar _tRpar_;

    public AParamlist()
    {
        // Constructor
    }

    public AParamlist(
        @SuppressWarnings("hiding") TTLpar _tLpar_,
        @SuppressWarnings("hiding") PTermlist _termlist_,
        @SuppressWarnings("hiding") TTRpar _tRpar_)
    {
        // Constructor
        setTLpar(_tLpar_);

        setTermlist(_termlist_);

        setTRpar(_tRpar_);

    }

    @Override
    public Object clone()
    {
        return new AParamlist(
            cloneNode(this._tLpar_),
            cloneNode(this._termlist_),
            cloneNode(this._tRpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamlist(this);
    }

    public TTLpar getTLpar()
    {
        return this._tLpar_;
    }

    public void setTLpar(TTLpar node)
    {
        if(this._tLpar_ != null)
        {
            this._tLpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLpar_ = node;
    }

    public PTermlist getTermlist()
    {
        return this._termlist_;
    }

    public void setTermlist(PTermlist node)
    {
        if(this._termlist_ != null)
        {
            this._termlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termlist_ = node;
    }

    public TTRpar getTRpar()
    {
        return this._tRpar_;
    }

    public void setTRpar(TTRpar node)
    {
        if(this._tRpar_ != null)
        {
            this._tRpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRpar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tLpar_)
            + toString(this._termlist_)
            + toString(this._tRpar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tLpar_ == child)
        {
            this._tLpar_ = null;
            return;
        }

        if(this._termlist_ == child)
        {
            this._termlist_ = null;
            return;
        }

        if(this._tRpar_ == child)
        {
            this._tRpar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tLpar_ == oldChild)
        {
            setTLpar((TTLpar) newChild);
            return;
        }

        if(this._termlist_ == oldChild)
        {
            setTermlist((PTermlist) newChild);
            return;
        }

        if(this._tRpar_ == oldChild)
        {
            setTRpar((TTRpar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
