/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AQuery extends PQuery
{
    private TTQuery _tQuery_;
    private PLitlist _litlist_;
    private TTDot _tDot_;

    public AQuery()
    {
        // Constructor
    }

    public AQuery(
        @SuppressWarnings("hiding") TTQuery _tQuery_,
        @SuppressWarnings("hiding") PLitlist _litlist_,
        @SuppressWarnings("hiding") TTDot _tDot_)
    {
        // Constructor
        setTQuery(_tQuery_);

        setLitlist(_litlist_);

        setTDot(_tDot_);

    }

    @Override
    public Object clone()
    {
        return new AQuery(
            cloneNode(this._tQuery_),
            cloneNode(this._litlist_),
            cloneNode(this._tDot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQuery(this);
    }

    public TTQuery getTQuery()
    {
        return this._tQuery_;
    }

    public void setTQuery(TTQuery node)
    {
        if(this._tQuery_ != null)
        {
            this._tQuery_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tQuery_ = node;
    }

    public PLitlist getLitlist()
    {
        return this._litlist_;
    }

    public void setLitlist(PLitlist node)
    {
        if(this._litlist_ != null)
        {
            this._litlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litlist_ = node;
    }

    public TTDot getTDot()
    {
        return this._tDot_;
    }

    public void setTDot(TTDot node)
    {
        if(this._tDot_ != null)
        {
            this._tDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tQuery_)
            + toString(this._litlist_)
            + toString(this._tDot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tQuery_ == child)
        {
            this._tQuery_ = null;
            return;
        }

        if(this._litlist_ == child)
        {
            this._litlist_ = null;
            return;
        }

        if(this._tDot_ == child)
        {
            this._tDot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tQuery_ == oldChild)
        {
            setTQuery((TTQuery) newChild);
            return;
        }

        if(this._litlist_ == oldChild)
        {
            setLitlist((PLitlist) newChild);
            return;
        }

        if(this._tDot_ == oldChild)
        {
            setTDot((TTDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
