/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class ARdftextTerm extends PTerm
{
    private TTPreRdftext _tPreRdftext_;
    private TTLpar _tLpar_;
    private TTStr _string_;
    private TTComma _tComma_;
    private TTStr _lang_;
    private TTRpar _tRpar_;

    public ARdftextTerm()
    {
        // Constructor
    }

    public ARdftextTerm(
        @SuppressWarnings("hiding") TTPreRdftext _tPreRdftext_,
        @SuppressWarnings("hiding") TTLpar _tLpar_,
        @SuppressWarnings("hiding") TTStr _string_,
        @SuppressWarnings("hiding") TTComma _tComma_,
        @SuppressWarnings("hiding") TTStr _lang_,
        @SuppressWarnings("hiding") TTRpar _tRpar_)
    {
        // Constructor
        setTPreRdftext(_tPreRdftext_);

        setTLpar(_tLpar_);

        setString(_string_);

        setTComma(_tComma_);

        setLang(_lang_);

        setTRpar(_tRpar_);

    }

    @Override
    public Object clone()
    {
        return new ARdftextTerm(
            cloneNode(this._tPreRdftext_),
            cloneNode(this._tLpar_),
            cloneNode(this._string_),
            cloneNode(this._tComma_),
            cloneNode(this._lang_),
            cloneNode(this._tRpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARdftextTerm(this);
    }

    public TTPreRdftext getTPreRdftext()
    {
        return this._tPreRdftext_;
    }

    public void setTPreRdftext(TTPreRdftext node)
    {
        if(this._tPreRdftext_ != null)
        {
            this._tPreRdftext_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPreRdftext_ = node;
    }

    public TTLpar getTLpar()
    {
        return this._tLpar_;
    }

    public void setTLpar(TTLpar node)
    {
        if(this._tLpar_ != null)
        {
            this._tLpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLpar_ = node;
    }

    public TTStr getString()
    {
        return this._string_;
    }

    public void setString(TTStr node)
    {
        if(this._string_ != null)
        {
            this._string_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._string_ = node;
    }

    public TTComma getTComma()
    {
        return this._tComma_;
    }

    public void setTComma(TTComma node)
    {
        if(this._tComma_ != null)
        {
            this._tComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tComma_ = node;
    }

    public TTStr getLang()
    {
        return this._lang_;
    }

    public void setLang(TTStr node)
    {
        if(this._lang_ != null)
        {
            this._lang_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lang_ = node;
    }

    public TTRpar getTRpar()
    {
        return this._tRpar_;
    }

    public void setTRpar(TTRpar node)
    {
        if(this._tRpar_ != null)
        {
            this._tRpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRpar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tPreRdftext_)
            + toString(this._tLpar_)
            + toString(this._string_)
            + toString(this._tComma_)
            + toString(this._lang_)
            + toString(this._tRpar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tPreRdftext_ == child)
        {
            this._tPreRdftext_ = null;
            return;
        }

        if(this._tLpar_ == child)
        {
            this._tLpar_ = null;
            return;
        }

        if(this._string_ == child)
        {
            this._string_ = null;
            return;
        }

        if(this._tComma_ == child)
        {
            this._tComma_ = null;
            return;
        }

        if(this._lang_ == child)
        {
            this._lang_ = null;
            return;
        }

        if(this._tRpar_ == child)
        {
            this._tRpar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tPreRdftext_ == oldChild)
        {
            setTPreRdftext((TTPreRdftext) newChild);
            return;
        }

        if(this._tLpar_ == oldChild)
        {
            setTLpar((TTLpar) newChild);
            return;
        }

        if(this._string_ == oldChild)
        {
            setString((TTStr) newChild);
            return;
        }

        if(this._tComma_ == oldChild)
        {
            setTComma((TTComma) newChild);
            return;
        }

        if(this._lang_ == oldChild)
        {
            setLang((TTStr) newChild);
            return;
        }

        if(this._tRpar_ == oldChild)
        {
            setTRpar((TTRpar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
