/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASqnamelTerm extends PTerm
{
    private TTPreSqname _tPreSqname_;
    private TTLpar _tLpar_;
    private TTSq _tSq_;
    private TTRpar _tRpar_;

    public ASqnamelTerm()
    {
        // Constructor
    }

    public ASqnamelTerm(
        @SuppressWarnings("hiding") TTPreSqname _tPreSqname_,
        @SuppressWarnings("hiding") TTLpar _tLpar_,
        @SuppressWarnings("hiding") TTSq _tSq_,
        @SuppressWarnings("hiding") TTRpar _tRpar_)
    {
        // Constructor
        setTPreSqname(_tPreSqname_);

        setTLpar(_tLpar_);

        setTSq(_tSq_);

        setTRpar(_tRpar_);

    }

    @Override
    public Object clone()
    {
        return new ASqnamelTerm(
            cloneNode(this._tPreSqname_),
            cloneNode(this._tLpar_),
            cloneNode(this._tSq_),
            cloneNode(this._tRpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASqnamelTerm(this);
    }

    public TTPreSqname getTPreSqname()
    {
        return this._tPreSqname_;
    }

    public void setTPreSqname(TTPreSqname node)
    {
        if(this._tPreSqname_ != null)
        {
            this._tPreSqname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPreSqname_ = node;
    }

    public TTLpar getTLpar()
    {
        return this._tLpar_;
    }

    public void setTLpar(TTLpar node)
    {
        if(this._tLpar_ != null)
        {
            this._tLpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLpar_ = node;
    }

    public TTSq getTSq()
    {
        return this._tSq_;
    }

    public void setTSq(TTSq node)
    {
        if(this._tSq_ != null)
        {
            this._tSq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSq_ = node;
    }

    public TTRpar getTRpar()
    {
        return this._tRpar_;
    }

    public void setTRpar(TTRpar node)
    {
        if(this._tRpar_ != null)
        {
            this._tRpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRpar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tPreSqname_)
            + toString(this._tLpar_)
            + toString(this._tSq_)
            + toString(this._tRpar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tPreSqname_ == child)
        {
            this._tPreSqname_ = null;
            return;
        }

        if(this._tLpar_ == child)
        {
            this._tLpar_ = null;
            return;
        }

        if(this._tSq_ == child)
        {
            this._tSq_ = null;
            return;
        }

        if(this._tRpar_ == child)
        {
            this._tRpar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tPreSqname_ == oldChild)
        {
            setTPreSqname((TTPreSqname) newChild);
            return;
        }

        if(this._tLpar_ == oldChild)
        {
            setTLpar((TTLpar) newChild);
            return;
        }

        if(this._tSq_ == oldChild)
        {
            setTSq((TTSq) newChild);
            return;
        }

        if(this._tRpar_ == oldChild)
        {
            setTRpar((TTRpar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
