/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AVarTerm extends PTerm
{
    private TTVariable _tVariable_;

    public AVarTerm()
    {
        // Constructor
    }

    public AVarTerm(
        @SuppressWarnings("hiding") TTVariable _tVariable_)
    {
        // Constructor
        setTVariable(_tVariable_);

    }

    @Override
    public Object clone()
    {
        return new AVarTerm(
            cloneNode(this._tVariable_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarTerm(this);
    }

    public TTVariable getTVariable()
    {
        return this._tVariable_;
    }

    public void setTVariable(TTVariable node)
    {
        if(this._tVariable_ != null)
        {
            this._tVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tVariable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tVariable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tVariable_ == child)
        {
            this._tVariable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tVariable_ == oldChild)
        {
            setTVariable((TTVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
