/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AXmlliteralTerm extends PTerm
{
    private TTPreXmlliteral _tPreXmlliteral_;
    private TTLpar _tLpar_;
    private TTStr _string_;
    private TTRpar _tRpar_;

    public AXmlliteralTerm()
    {
        // Constructor
    }

    public AXmlliteralTerm(
        @SuppressWarnings("hiding") TTPreXmlliteral _tPreXmlliteral_,
        @SuppressWarnings("hiding") TTLpar _tLpar_,
        @SuppressWarnings("hiding") TTStr _string_,
        @SuppressWarnings("hiding") TTRpar _tRpar_)
    {
        // Constructor
        setTPreXmlliteral(_tPreXmlliteral_);

        setTLpar(_tLpar_);

        setString(_string_);

        setTRpar(_tRpar_);

    }

    @Override
    public Object clone()
    {
        return new AXmlliteralTerm(
            cloneNode(this._tPreXmlliteral_),
            cloneNode(this._tLpar_),
            cloneNode(this._string_),
            cloneNode(this._tRpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXmlliteralTerm(this);
    }

    public TTPreXmlliteral getTPreXmlliteral()
    {
        return this._tPreXmlliteral_;
    }

    public void setTPreXmlliteral(TTPreXmlliteral node)
    {
        if(this._tPreXmlliteral_ != null)
        {
            this._tPreXmlliteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPreXmlliteral_ = node;
    }

    public TTLpar getTLpar()
    {
        return this._tLpar_;
    }

    public void setTLpar(TTLpar node)
    {
        if(this._tLpar_ != null)
        {
            this._tLpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLpar_ = node;
    }

    public TTStr getString()
    {
        return this._string_;
    }

    public void setString(TTStr node)
    {
        if(this._string_ != null)
        {
            this._string_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._string_ = node;
    }

    public TTRpar getTRpar()
    {
        return this._tRpar_;
    }

    public void setTRpar(TTRpar node)
    {
        if(this._tRpar_ != null)
        {
            this._tRpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRpar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tPreXmlliteral_)
            + toString(this._tLpar_)
            + toString(this._string_)
            + toString(this._tRpar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tPreXmlliteral_ == child)
        {
            this._tPreXmlliteral_ = null;
            return;
        }

        if(this._tLpar_ == child)
        {
            this._tLpar_ = null;
            return;
        }

        if(this._string_ == child)
        {
            this._string_ = null;
            return;
        }

        if(this._tRpar_ == child)
        {
            this._tRpar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tPreXmlliteral_ == oldChild)
        {
            setTPreXmlliteral((TTPreXmlliteral) newChild);
            return;
        }

        if(this._tLpar_ == oldChild)
        {
            setTLpar((TTLpar) newChild);
            return;
        }

        if(this._string_ == oldChild)
        {
            setString((TTStr) newChild);
            return;
        }

        if(this._tRpar_ == oldChild)
        {
            setTRpar((TTRpar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
