/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTPreGmonthday extends Token
{
    public TTPreGmonthday()
    {
        super.setText("_gmonthday");
    }

    public TTPreGmonthday(int line, int pos)
    {
        super.setText("_gmonthday");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPreGmonthday(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPreGmonthday(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPreGmonthday text.");
    }
}
