/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTPreXmlliteral extends Token
{
    public TTPreXmlliteral()
    {
        super.setText("_xmlliteral");
    }

    public TTPreXmlliteral(int line, int pos)
    {
        super.setText("_xmlliteral");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPreXmlliteral(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPreXmlliteral(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPreXmlliteral text.");
    }
}
