/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTPreYearmonthduration extends Token
{
    public TTPreYearmonthduration()
    {
        super.setText("_yearmonthduration");
    }

    public TTPreYearmonthduration(int line, int pos)
    {
        super.setText("_yearmonthduration");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPreYearmonthduration(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPreYearmonthduration(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPreYearmonthduration text.");
    }
}
